package equations;

/**
 * ForceEquation class for the Apollo Targeting Interface
 * @author Braidan Duffy
 *
 */
public class ForceEquation {
	public double mass, velocity, force;
	
	/**
	 * Constructor for the force equation
	 * @param m the mass of the projectile
	 * @param v the velocity of the projectile
	 */
	public ForceEquation(double m, double v) {
		mass = m; velocity = v;
	}
	 
	/**
	* Method that calculates the force generated by given parameters
	*/
	public void calcEquation() {
		force = mass * velocity;
	}
}
